#!/usr/bin/env node
/**
 * Regenerate src/lib/schemas-embedded.ts from docs/schemas/*.schema.json.
 *
 * The CLI bundle embeds all canonical v3 schemas at build time. This script
 * reads every *.schema.json under docs/schemas/, derives a stable name for
 * each (file stem with `.schema` stripped), and writes a TypeScript module
 * that exports them as a name→object map.
 *
 * Run via: npm run schemas:regen (from src/cli/)
 */

import * as fs from 'fs';
import * as path from 'path';
import { fileURLToPath } from 'url';

const here = path.dirname(fileURLToPath(import.meta.url));
const repoRoot = path.resolve(here, '..', '..', '..');
const schemasDir = path.resolve(repoRoot, 'docs', 'schemas');
const outFile = path.resolve(here, '..', 'src', 'lib', 'schemas-embedded.ts');

function schemaNameFromFile(filename) {
  // "task-contract.schema.json" -> "task-contract"
  return filename.replace(/\.schema\.json$/, '');
}

const files = fs
  .readdirSync(schemasDir)
  .filter((f) => f.endsWith('.schema.json'))
  .sort();

if (files.length === 0) {
  console.error(`No schemas found in ${schemasDir}`);
  process.exit(1);
}

const entries = [];
for (const file of files) {
  const name = schemaNameFromFile(file);
  const content = fs.readFileSync(path.join(schemasDir, file), 'utf-8');
  const parsed = JSON.parse(content);
  entries.push({ name, schema: parsed, file });
}

const header = [
  '/**',
  ' * Embedded JSON Schema registry (generated).',
  ' *',
  ' * Do NOT edit this file by hand. Regenerate with:',
  ' *   cd src/cli && npm run schemas:regen',
  ' *',
  ' * Source: docs/schemas/*.schema.json',
  ' */',
  '',
  '/* eslint-disable */',
  '',
].join('\n');

const body = [];
body.push('export const SCHEMAS: Record<string, unknown> = {');
for (const { name, schema } of entries) {
  body.push(`  ${JSON.stringify(name)}: ${JSON.stringify(schema)},`);
}
body.push('};');
body.push('');
body.push('export const SCHEMA_NAMES: readonly string[] = [');
for (const { name } of entries) {
  body.push(`  ${JSON.stringify(name)},`);
}
body.push('];');
body.push('');

fs.writeFileSync(outFile, header + body.join('\n'));

console.log(`Regenerated ${outFile}`);
console.log(`  ${entries.length} schemas embedded:`);
for (const { name } of entries) {
  console.log(`   - ${name}`);
}
